DROP TABLE IF EXISTS `menu_builder_offers`;
CREATE TABLE IF NOT EXISTS `menu_builder_offers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `people` int(10) unsigned DEFAULT NULL,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_offers_products`;
CREATE TABLE IF NOT EXISTS `menu_builder_offers_products` (
  `offer_id` int(10) unsigned NOT NULL DEFAULT '0',
  `product_id` int(10) unsigned NOT NULL DEFAULT '0',
  `size_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`offer_id`,`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_products`;
CREATE TABLE IF NOT EXISTS `menu_builder_products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` int(10) unsigned DEFAULT NULL,
  `parent_category_id` int(10) unsigned DEFAULT NULL,
  `set_different_sizes` enum('T','F') DEFAULT 'F',
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `order` int(10) unsigned DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_products_prices`;
CREATE TABLE IF NOT EXISTS `menu_builder_products_prices` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,	
  `product_id` int(10) unsigned DEFAULT NULL,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_products_categories`;
CREATE TABLE IF NOT EXISTS `menu_builder_products_categories` (
  `product_id` int(10) unsigned NOT NULL DEFAULT '0',
  `category_id` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`product_id`,`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_categories`;
CREATE TABLE IF NOT EXISTS `menu_builder_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `order` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_fields`;
CREATE TABLE IF NOT EXISTS `menu_builder_fields` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(100) DEFAULT NULL,
  `type` enum('backend','frontend','arrays') DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  `source` enum('script','plugin') DEFAULT 'script',
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_multi_lang`;
CREATE TABLE IF NOT EXISTS `menu_builder_multi_lang` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `foreign_id` int(10) unsigned DEFAULT NULL,
  `model` varchar(50) DEFAULT NULL,
  `locale` tinyint(3) unsigned DEFAULT NULL,
  `field` varchar(50) DEFAULT NULL,
  `content` text,
  `source` enum('script','plugin','data') DEFAULT 'script',
  PRIMARY KEY (`id`),
  UNIQUE KEY `foreign_id` (`foreign_id`,`model`,`locale`,`field`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_options`;
CREATE TABLE IF NOT EXISTS `menu_builder_options` (
  `foreign_id` int(10) unsigned NOT NULL DEFAULT '0',
  `key` varchar(255) NOT NULL DEFAULT '',
  `tab_id` tinyint(3) unsigned DEFAULT NULL,
  `value` text,
  `label` text,
  `type` enum('string','text','int','float','enum','bool') NOT NULL DEFAULT 'string',
  `order` int(10) unsigned DEFAULT NULL,
  `is_visible` tinyint(1) unsigned DEFAULT '1',
  `style` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`foreign_id`,`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_roles`;
CREATE TABLE IF NOT EXISTS `menu_builder_roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `menu_builder_users`;
CREATE TABLE IF NOT EXISTS `menu_builder_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(10) unsigned NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` blob,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `created` datetime NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  `is_active` enum('T','F') NOT NULL DEFAULT 'F',
  `ip` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `role_id` (`role_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `menu_builder_fields` (`id`, `key`, `type`, `label`, `source`, `modified`) VALUES
(1, 'addLocale', 'backend', 'Add language', 'script', NULL),
(2, 'adminForgot', 'backend', 'Forgot password', 'script', NULL),
(3, 'adminLogin', 'backend', 'Admin Login', 'script', NULL),
(4, 'backend', 'backend', 'Backend titles', 'script', NULL),
(5, 'btnAdd', 'backend', 'Button Add', 'script', NULL),
(6, 'btnBack', 'backend', 'Button Back', 'script', NULL),
(7, 'btnBackup', 'backend', 'Button Backup', 'script', NULL),
(8, 'btnCancel', 'backend', 'Button Cancel', 'script', NULL),
(9, 'btnContinue', 'backend', 'Button Continue', 'script', NULL),
(10, 'btnDelete', 'backend', 'Button Delete', 'script', NULL),
(11, 'btnLogin', 'backend', 'Login', 'script', NULL),
(12, 'btnReset', 'backend', 'Reset', 'script', NULL),
(13, 'btnSave', 'backend', 'Save', 'script', NULL),
(14, 'btnSearch', 'backend', 'Search', 'script', NULL),
(15, 'btnSend', 'backend', 'Button Send', 'script', NULL),
(16, 'btnUpdate', 'backend', 'Update', 'script', NULL),
(17, 'created', 'backend', 'Created', 'script', NULL),
(18, 'email', 'backend', 'E-Mail', 'script', NULL),
(19, 'emailForgotBody', 'backend', 'Email / Forgot Body', 'script', NULL),
(20, 'emailForgotSubject', 'backend', 'Email / Forgot Subject', 'script', NULL),
(21, 'frontend', 'backend', 'Front-end titles', 'script', NULL),
(22, 'gridActionTitle', 'backend', 'Grid / Action Title', 'script', NULL),
(23, 'gridBtnCancel', 'backend', 'Grid / Button Cancel', 'script', NULL),
(24, 'gridBtnDelete', 'backend', 'Grid / Button Delete', 'script', NULL),
(25, 'gridBtnOk', 'backend', 'Grid / Button OK', 'script', NULL),
(26, 'gridChooseAction', 'backend', 'Grid / Choose Action', 'script', NULL),
(27, 'gridConfirmationTitle', 'backend', 'Grid / Confirmation Title', 'script', NULL),
(28, 'gridDeleteConfirmation', 'backend', 'Grid / Delete confirmation', 'script', NULL),
(29, 'gridEmptyResult', 'backend', 'Grid / Empty resultset', 'script', NULL),
(30, 'gridGotoPage', 'backend', 'Grid / Go to page', 'script', NULL),
(31, 'gridItemsPerPage', 'backend', 'Grid / Items per page', 'script', NULL),
(32, 'gridNext', 'backend', 'Grid / Next', 'script', NULL),
(33, 'gridNextPage', 'backend', 'Grid / Next page', 'script', NULL),
(34, 'gridPrev', 'backend', 'Grid / Prev', 'script', NULL),
(35, 'gridPrevPage', 'backend', 'Grid / Prev page', 'script', NULL),
(36, 'gridTotalItems', 'backend', 'Grid / Total items', 'script', NULL),
(37, 'infoListingAddressBody', 'backend', 'Infobox / Listing Address Body', 'script', NULL),
(38, 'infoListingAddressTitle', 'backend', 'Infobox / Listing Address Title', 'script', NULL),
(39, 'infoListingBookingsBody', 'backend', 'Infobox / Listing Bookings Body', 'script', NULL),
(40, 'infoListingBookingsTitle', 'backend', 'Infobox / Listing Bookings Title', 'script', NULL),
(41, 'infoListingContactBody', 'backend', 'Infobox / Listing Contact Body', 'script', NULL),
(42, 'infoListingContactTitle', 'backend', 'Infobox / Listing Contact Title', 'script', NULL),
(43, 'infoListingExtendBody', 'backend', 'Infobox / Extend exp.date Body', 'script', NULL),
(44, 'infoListingExtendTitle', 'backend', 'Infobox / Extend exp.date Title', 'script', NULL),
(45, 'infoListingPricesBody', 'backend', 'Infobox / Listing Prices Body', 'script', NULL),
(46, 'infoListingPricesTitle', 'backend', 'Infobox / Listing Prices Title', 'script', NULL),
(47, 'infoLocalesArraysBody', 'backend', 'Locale / Languages Array Body', 'script', NULL),
(48, 'infoLocalesArraysTitle', 'backend', 'Locale / Languages Array Title', 'script', NULL),
(49, 'infoLocalesBackendBody', 'backend', 'Infobox / Locales Backend Body', 'script', NULL),
(50, 'infoLocalesBackendTitle', 'backend', 'Infobox / Locales Backend Title', 'script', NULL),
(51, 'infoLocalesBody', 'backend', 'Infobox / Locales Body', 'script', NULL),
(52, 'infoLocalesFrontendBody', 'backend', 'Infobox / Locales Frontend Body', 'script', NULL),
(53, 'infoLocalesFrontendTitle', 'backend', 'Infobox / Locales Frontend Title', 'script', NULL),
(54, 'infoLocalesTitle', 'backend', 'Infobox / Locales Title', 'script', NULL),
(55, 'lblAddUser', 'backend', 'Add user', 'script', NULL),
(56, 'lblBackupDatabase', 'backend', 'Backup / Database', 'script', NULL),
(57, 'lblBackupFiles', 'backend', 'Backup / Files', 'script', NULL),
(58, 'lblChoose', 'backend', 'Choose', 'script', NULL),
(59, 'lblDays', 'backend', 'Days', 'script', NULL),
(60, 'lblDelete', 'backend', 'Delete', 'script', NULL),
(61, 'lblError', 'backend', 'Error', 'script', NULL),
(62, 'lblExport', 'backend', 'Export', 'script', NULL),
(63, 'lblForgot', 'backend', 'Forgot password', 'script', NULL),
(64, 'lblIp', 'backend', 'IP address', 'script', NULL),
(65, 'lblIsActive', 'backend', 'Is Active', 'script', NULL),
(66, 'lblName', 'backend', 'Name', 'script', NULL),
(67, 'lblNo', 'backend', 'No', 'script', NULL),
(68, 'lblOption', 'backend', 'Option', 'script', NULL),
(69, 'lblOptionList', 'backend', 'Option list', 'script', NULL),
(70, 'lblRole', 'backend', 'Role', 'script', NULL),
(71, 'lblStatus', 'backend', 'Status', 'script', NULL),
(72, 'lblType', 'backend', 'Type', 'script', NULL),
(73, 'lblUpdateUser', 'backend', 'Update user', 'script', NULL),
(74, 'lblUserCreated', 'backend', 'User / Registration Date & Time', 'script', NULL),
(75, 'lblValue', 'backend', 'Value', 'script', NULL),
(76, 'lblYes', 'backend', 'Yes', 'script', NULL),
(77, 'lnkBack', 'backend', 'Link Back', 'script', NULL),
(78, 'localeArrays', 'backend', 'Locale / Arrays titles', 'script', NULL),
(79, 'locales', 'backend', 'Languages', 'script', NULL),
(80, 'locale_flag', 'backend', 'Locale / Flag', 'script', NULL),
(81, 'locale_is_default', 'backend', 'Locale / Is default', 'script', NULL),
(82, 'locale_order', 'backend', 'Locale / Order', 'script', NULL),
(83, 'locale_title', 'backend', 'Locale / Title', 'script', NULL),
(84, 'menuBackup', 'backend', 'Menu Backup', 'script', NULL),
(85, 'menuDashboard', 'backend', 'Menu Dashboard', 'script', NULL),
(86, 'menuLang', 'backend', 'Menu Multi lang', 'script', NULL),
(87, 'menuLocales', 'backend', 'Menu Languages', 'script', NULL),
(88, 'menuLogout', 'backend', 'Menu Logout', 'script', NULL),
(89, 'menuOptions', 'backend', 'Menu Options', 'script', NULL),
(90, 'menuPlugins', 'backend', 'Menu Plugins', 'script', NULL),
(91, 'menuProfile', 'backend', 'Menu Profile', 'script', NULL),
(92, 'menuUsers', 'backend', 'Menu Users', 'script', NULL),
(93, 'multilangTooltip', 'backend', 'MultiLang / Tooltip', 'script', NULL),
(94, 'opt_o_currency', 'backend', 'Options / Currency', 'script', NULL),
(95, 'opt_o_date_format', 'backend', 'Options / Date format', 'script', NULL),
(96, 'opt_o_send_email', 'backend', 'opt_o_send_email', 'script', NULL),
(97, 'opt_o_smtp_host', 'backend', 'opt_o_smtp_host', 'script', NULL),
(98, 'opt_o_smtp_pass', 'backend', 'opt_o_smtp_pass', 'script', NULL),
(99, 'opt_o_smtp_port', 'backend', 'opt_o_smtp_port', 'script', NULL),
(100, 'opt_o_smtp_user', 'backend', 'opt_o_smtp_user', 'script', NULL),
(101, 'opt_o_timezone', 'backend', 'Options / Timezone', 'script', NULL),
(102, 'opt_o_week_start', 'backend', 'Options / First day of the week', 'script', NULL),
(103, 'pass', 'backend', 'Password', 'script', NULL),
(125, 'revert_status', 'backend', 'Revert status', 'script', NULL),
(126, 'url', 'backend', 'URL', 'script', NULL),
(127, 'user', 'backend', 'Username', 'script', NULL),
(128, 'pj_email_taken', 'backend', 'Users / Email already taken', 'script', NULL),
(129, 'days_ARRAY_0', 'arrays', 'days_ARRAY_0', 'script', NULL),
(130, 'days_ARRAY_1', 'arrays', 'days_ARRAY_1', 'script', NULL),
(131, 'days_ARRAY_2', 'arrays', 'days_ARRAY_2', 'script', NULL),
(132, 'days_ARRAY_3', 'arrays', 'days_ARRAY_3', 'script', NULL),
(133, 'days_ARRAY_4', 'arrays', 'days_ARRAY_4', 'script', NULL),
(134, 'days_ARRAY_5', 'arrays', 'days_ARRAY_5', 'script', NULL),
(135, 'days_ARRAY_6', 'arrays', 'days_ARRAY_6', 'script', NULL),
(136, 'day_names_ARRAY_0', 'arrays', 'day_names_ARRAY_0', 'script', NULL),
(137, 'day_names_ARRAY_1', 'arrays', 'day_names_ARRAY_1', 'script', NULL),
(138, 'day_names_ARRAY_2', 'arrays', 'day_names_ARRAY_2', 'script', NULL),
(139, 'day_names_ARRAY_3', 'arrays', 'day_names_ARRAY_3', 'script', NULL),
(140, 'day_names_ARRAY_4', 'arrays', 'day_names_ARRAY_4', 'script', NULL),
(141, 'day_names_ARRAY_5', 'arrays', 'day_names_ARRAY_5', 'script', NULL),
(142, 'day_names_ARRAY_6', 'arrays', 'day_names_ARRAY_6', 'script', NULL),
(143, 'error_bodies_ARRAY_AA10', 'arrays', 'error_bodies_ARRAY_AA10', 'script', NULL),
(144, 'error_bodies_ARRAY_AA11', 'arrays', 'error_bodies_ARRAY_AA11', 'script', NULL),
(145, 'error_bodies_ARRAY_AA12', 'arrays', 'error_bodies_ARRAY_AA12', 'script', NULL),
(146, 'error_bodies_ARRAY_AA13', 'arrays', 'error_bodies_ARRAY_AA13', 'script', NULL),
(147, 'error_bodies_ARRAY_AB01', 'arrays', 'error_bodies_ARRAY_AB01', 'script', NULL),
(148, 'error_bodies_ARRAY_AB02', 'arrays', 'error_bodies_ARRAY_AB02', 'script', NULL),
(149, 'error_bodies_ARRAY_AB03', 'arrays', 'error_bodies_ARRAY_AB03', 'script', NULL),
(150, 'error_bodies_ARRAY_AB04', 'arrays', 'error_bodies_ARRAY_AB04', 'script', NULL),
(151, 'error_bodies_ARRAY_ALC01', 'arrays', 'error_bodies_ARRAY_ALC01', 'script', NULL),
(152, 'error_bodies_ARRAY_AO01', 'arrays', 'error_bodies_ARRAY_AO01', 'script', NULL),
(153, 'error_bodies_ARRAY_AU01', 'arrays', 'error_bodies_ARRAY_AU01', 'script', NULL),
(154, 'error_bodies_ARRAY_AU03', 'arrays', 'error_bodies_ARRAY_AU03', 'script', NULL),
(155, 'error_bodies_ARRAY_AU04', 'arrays', 'error_bodies_ARRAY_AU04', 'script', NULL),
(156, 'error_bodies_ARRAY_AU08', 'arrays', 'error_bodies_ARRAY_AU08', 'script', NULL),
(159, 'error_titles_ARRAY_AA10', 'arrays', 'error_titles_ARRAY_AA10', 'script', NULL),
(160, 'error_titles_ARRAY_AA11', 'arrays', 'error_titles_ARRAY_AA11', 'script', NULL),
(161, 'error_titles_ARRAY_AA12', 'arrays', 'error_titles_ARRAY_AA12', 'script', NULL),
(162, 'error_titles_ARRAY_AA13', 'arrays', 'error_titles_ARRAY_AA13', 'script', NULL),
(163, 'error_titles_ARRAY_AB01', 'arrays', 'error_titles_ARRAY_AB01', 'script', NULL),
(164, 'error_titles_ARRAY_AB02', 'arrays', 'error_titles_ARRAY_AB02', 'script', NULL),
(165, 'error_titles_ARRAY_AB03', 'arrays', 'error_titles_ARRAY_AB03', 'script', NULL),
(166, 'error_titles_ARRAY_AB04', 'arrays', 'error_titles_ARRAY_AB04', 'script', NULL),
(167, 'error_titles_ARRAY_AO01', 'arrays', 'error_titles_ARRAY_AO01', 'script', NULL),
(168, 'error_titles_ARRAY_AU01', 'arrays', 'error_titles_ARRAY_AU01', 'script', NULL),
(169, 'error_titles_ARRAY_AU03', 'arrays', 'error_titles_ARRAY_AU03', 'script', NULL),
(170, 'error_titles_ARRAY_AU04', 'arrays', 'error_titles_ARRAY_AU04', 'script', NULL),
(171, 'error_titles_ARRAY_AU08', 'arrays', 'error_titles_ARRAY_AU08', 'script', NULL),
(174, 'filter_ARRAY_active', 'arrays', 'filter_ARRAY_active', 'script', NULL),
(175, 'filter_ARRAY_inactive', 'arrays', 'filter_ARRAY_inactive', 'script', NULL),
(176, 'login_err_ARRAY_1', 'arrays', 'login_err_ARRAY_1', 'script', NULL),
(177, 'login_err_ARRAY_2', 'arrays', 'login_err_ARRAY_2', 'script', NULL),
(178, 'login_err_ARRAY_3', 'arrays', 'login_err_ARRAY_3', 'script', NULL),
(179, 'months_ARRAY_1', 'arrays', 'months_ARRAY_1', 'script', NULL),
(180, 'months_ARRAY_10', 'arrays', 'months_ARRAY_10', 'script', NULL),
(181, 'months_ARRAY_11', 'arrays', 'months_ARRAY_11', 'script', NULL),
(182, 'months_ARRAY_12', 'arrays', 'months_ARRAY_12', 'script', NULL),
(183, 'months_ARRAY_2', 'arrays', 'months_ARRAY_2', 'script', NULL),
(184, 'months_ARRAY_3', 'arrays', 'months_ARRAY_3', 'script', NULL),
(185, 'months_ARRAY_4', 'arrays', 'months_ARRAY_4', 'script', NULL),
(186, 'months_ARRAY_5', 'arrays', 'months_ARRAY_5', 'script', NULL),
(187, 'months_ARRAY_6', 'arrays', 'months_ARRAY_6', 'script', NULL),
(188, 'months_ARRAY_7', 'arrays', 'months_ARRAY_7', 'script', NULL),
(189, 'months_ARRAY_8', 'arrays', 'months_ARRAY_8', 'script', NULL),
(190, 'months_ARRAY_9', 'arrays', 'months_ARRAY_9', 'script', NULL),
(191, 'personal_titles_ARRAY_dr', 'arrays', 'personal_titles_ARRAY_dr', 'script', NULL),
(192, 'personal_titles_ARRAY_miss', 'arrays', 'personal_titles_ARRAY_miss', 'script', NULL),
(193, 'personal_titles_ARRAY_mr', 'arrays', 'personal_titles_ARRAY_mr', 'script', NULL),
(194, 'personal_titles_ARRAY_mrs', 'arrays', 'personal_titles_ARRAY_mrs', 'script', NULL),
(195, 'personal_titles_ARRAY_ms', 'arrays', 'personal_titles_ARRAY_ms', 'script', NULL),
(196, 'personal_titles_ARRAY_other', 'arrays', 'personal_titles_ARRAY_other', 'script', NULL),
(197, 'personal_titles_ARRAY_prof', 'arrays', 'personal_titles_ARRAY_prof', 'script', NULL),
(198, 'personal_titles_ARRAY_rev', 'arrays', 'personal_titles_ARRAY_rev', 'script', NULL),
(199, 'short_months_ARRAY_1', 'arrays', 'short_months_ARRAY_1', 'script', NULL),
(200, 'short_months_ARRAY_10', 'arrays', 'short_months_ARRAY_10', 'script', NULL),
(201, 'short_months_ARRAY_11', 'arrays', 'short_months_ARRAY_11', 'script', NULL),
(202, 'short_months_ARRAY_12', 'arrays', 'short_months_ARRAY_12', 'script', NULL),
(203, 'short_months_ARRAY_2', 'arrays', 'short_months_ARRAY_2', 'script', NULL),
(204, 'short_months_ARRAY_3', 'arrays', 'short_months_ARRAY_3', 'script', NULL),
(205, 'short_months_ARRAY_4', 'arrays', 'short_months_ARRAY_4', 'script', NULL),
(206, 'short_months_ARRAY_5', 'arrays', 'short_months_ARRAY_5', 'script', NULL),
(207, 'short_months_ARRAY_6', 'arrays', 'short_months_ARRAY_6', 'script', NULL),
(208, 'short_months_ARRAY_7', 'arrays', 'short_months_ARRAY_7', 'script', NULL),
(209, 'short_months_ARRAY_8', 'arrays', 'short_months_ARRAY_8', 'script', NULL),
(210, 'short_months_ARRAY_9', 'arrays', 'short_months_ARRAY_9', 'script', NULL),
(211, 'status_ARRAY_1', 'arrays', 'status_ARRAY_1', 'script', NULL),
(212, 'status_ARRAY_123', 'arrays', 'status_ARRAY_123', 'script', NULL),
(213, 'status_ARRAY_2', 'arrays', 'status_ARRAY_2', 'script', NULL),
(214, 'status_ARRAY_3', 'arrays', 'status_ARRAY_3', 'script', NULL),
(215, 'status_ARRAY_7', 'arrays', 'status_ARRAY_7', 'script', NULL),
(216, 'status_ARRAY_996', 'arrays', 'status_ARRAY_996', 'script', NULL),
(217, 'status_ARRAY_997', 'arrays', 'status_ARRAY_997', 'script', NULL),
(218, 'status_ARRAY_998', 'arrays', 'status_ARRAY_998', 'script', NULL),
(219, 'status_ARRAY_999', 'arrays', 'status_ARRAY_999', 'script', NULL),
(220, 'status_ARRAY_9997', 'arrays', 'status_ARRAY_9997', 'script', NULL),
(221, 'status_ARRAY_9998', 'arrays', 'status_ARRAY_9998', 'script', NULL),
(222, 'status_ARRAY_9999', 'arrays', 'status_ARRAY_9999', 'script', NULL),
(223, 'timezones_ARRAY_-10800', 'arrays', 'timezones_ARRAY_-10800', 'script', NULL),
(224, 'timezones_ARRAY_-14400', 'arrays', 'timezones_ARRAY_-14400', 'script', NULL),
(225, 'timezones_ARRAY_-18000', 'arrays', 'timezones_ARRAY_-18000', 'script', NULL),
(226, 'timezones_ARRAY_-21600', 'arrays', 'timezones_ARRAY_-21600', 'script', NULL),
(227, 'timezones_ARRAY_-25200', 'arrays', 'timezones_ARRAY_-25200', 'script', NULL),
(228, 'timezones_ARRAY_-28800', 'arrays', 'timezones_ARRAY_-28800', 'script', NULL),
(229, 'timezones_ARRAY_-32400', 'arrays', 'timezones_ARRAY_-32400', 'script', NULL),
(230, 'timezones_ARRAY_-3600', 'arrays', 'timezones_ARRAY_-3600', 'script', NULL),
(231, 'timezones_ARRAY_-36000', 'arrays', 'timezones_ARRAY_-36000', 'script', NULL),
(232, 'timezones_ARRAY_-39600', 'arrays', 'timezones_ARRAY_-39600', 'script', NULL),
(233, 'timezones_ARRAY_-43200', 'arrays', 'timezones_ARRAY_-43200', 'script', NULL),
(234, 'timezones_ARRAY_-7200', 'arrays', 'timezones_ARRAY_-7200', 'script', NULL),
(235, 'timezones_ARRAY_0', 'arrays', 'timezones_ARRAY_0', 'script', NULL),
(236, 'timezones_ARRAY_10800', 'arrays', 'timezones_ARRAY_10800', 'script', NULL),
(237, 'timezones_ARRAY_14400', 'arrays', 'timezones_ARRAY_14400', 'script', NULL),
(238, 'timezones_ARRAY_18000', 'arrays', 'timezones_ARRAY_18000', 'script', NULL),
(239, 'timezones_ARRAY_21600', 'arrays', 'timezones_ARRAY_21600', 'script', NULL),
(240, 'timezones_ARRAY_25200', 'arrays', 'timezones_ARRAY_25200', 'script', NULL),
(241, 'timezones_ARRAY_28800', 'arrays', 'timezones_ARRAY_28800', 'script', NULL),
(242, 'timezones_ARRAY_32400', 'arrays', 'timezones_ARRAY_32400', 'script', NULL),
(243, 'timezones_ARRAY_3600', 'arrays', 'timezones_ARRAY_3600', 'script', NULL),
(244, 'timezones_ARRAY_36000', 'arrays', 'timezones_ARRAY_36000', 'script', NULL),
(245, 'timezones_ARRAY_39600', 'arrays', 'timezones_ARRAY_39600', 'script', NULL),
(246, 'timezones_ARRAY_43200', 'arrays', 'timezones_ARRAY_43200', 'script', NULL),
(247, 'timezones_ARRAY_46800', 'arrays', 'timezones_ARRAY_46800', 'script', NULL),
(248, 'timezones_ARRAY_7200', 'arrays', 'timezones_ARRAY_7200', 'script', NULL),
(249, 'u_statarr_ARRAY_F', 'arrays', 'u_statarr_ARRAY_F', 'script', NULL),
(250, 'u_statarr_ARRAY_T', 'arrays', 'u_statarr_ARRAY_T', 'script', NULL),
(251, '_yesno_ARRAY_F', 'arrays', '_yesno_ARRAY_F', 'script', NULL),
(252, '_yesno_ARRAY_T', 'arrays', '_yesno_ARRAY_T', 'script', NULL),
(253, 'delete_selected', 'backend', 'Label / Delete selected', 'script', NULL),
(254, 'delete_confirmation', 'backend', 'Label / delete confirmation', 'script', NULL),
(255, 'lblAll', 'backend', 'Label / All', 'script', NULL),
(256, 'email_taken', 'backend', 'Label / email taken', 'script', NULL),
(308, 'lblDashLastLogin', 'backend', 'Label / Last login', 'script', NULL),
(360, 'menuInstall', 'backend', 'Menu / Install', 'script', NULL),
(361, 'menuPreview', 'backend', 'Menu / Preview', 'script', NULL),
(480, 'infoUsersTitle', 'backend', 'Infobox / List of users', 'script', NULL),
(481, 'infoUsersDesc', 'backend', 'Infobox / List of users', 'script', NULL),
(482, 'btnAddUser', 'backend', 'Button / + Add user', 'script', NULL),
(483, 'gridEmptyTitle', 'backend', 'Grid / No records selected', 'script', NULL),
(484, 'gridEmptyBody', 'backend', 'Grid / You need to select at least a single record.', 'script', NULL),
(485, 'infoAddUserTitle', 'backend', 'Infobox / Add user', 'script', NULL),
(486, 'infoAddUserDesc', 'backend', 'Infobox / Add user', 'script', '2015-06-18 11:35:17'),
(487, 'lblPhone', 'backend', 'Label / Phone', 'script', NULL),
(488, 'infoUpdateUserTitle', 'backend', 'Infobox / Update user', 'script', NULL),
(489, 'infoUpdateUserDesc', 'backend', 'Infobox / Update user', 'script', NULL),
(490, 'menuGeneral', 'backend', 'Menu / General', 'script', NULL),
(491, 'infoGeneralTitle', 'backend', 'Infobox / General options', 'script', NULL),
(492, 'infoGeneralDesc', 'backend', 'Infobox / General options', 'script', NULL),
(493, 'opt_o_time_format', 'backend', 'Options / Time format', 'script', NULL),
(494, 'menuProducts', 'backend', 'Menu / Products', 'script', NULL),
(495, 'menuCategories', 'backend', 'Menu / Categories', 'script', NULL),
(496, 'menuSpecialOffers', 'backend', 'Menu / Special offers', 'script', NULL),
(497, 'btnAddCategory', 'backend', 'Button / + Add category', 'script', NULL),
(498, 'infoCategoriesTitle', 'backend', 'Infobox / List of categories', 'script', '2015-06-18 11:30:50'),
(499, 'infoCategoriesDesc', 'backend', 'Infobox / List of categories', 'script', '2015-06-18 11:31:19'),
(500, 'lblCategoryTitle', 'backend', 'Label / Category title', 'script', NULL),
(501, 'lblFieldRequired', 'backend', 'Label / This field is required.', 'script', NULL),
(502, 'lblSameCategory', 'backend', 'Label / Category title is already used.', 'script', NULL),
(503, 'infoAddCategoryTitle', 'backend', 'Infobox / Add category', 'script', NULL),
(504, 'infoAddCategoryDesc', 'backend', 'Infobox / Add category', 'script', '2015-06-18 11:32:26'),
(505, 'lblParentCategory', 'backend', 'Label / Parent category', 'script', NULL),
(506, 'lblImage', 'backend', 'Label / Image', 'script', NULL),
(507, 'error_titles_ARRAY_ACT01', 'arrays', 'error_titles_ARRAY_ACT01', 'script', NULL),
(508, 'error_bodies_ARRAY_ACT01', 'arrays', 'error_bodies_ARRAY_ACT01', 'script', NULL),
(509, 'error_titles_ARRAY_ACT03', 'arrays', 'error_titles_ARRAY_ACT03', 'script', NULL),
(510, 'error_bodies_ARRAY_ACT03', 'arrays', 'error_bodies_ARRAY_ACT03', 'script', '2015-06-18 11:35:54'),
(511, 'error_titles_ARRAY_ACT04', 'arrays', 'error_titles_ARRAY_ACT04', 'script', NULL),
(512, 'error_bodies_ARRAY_ACT04', 'arrays', 'error_bodies_ARRAY_ACT04', 'script', NULL),
(513, 'error_titles_ARRAY_ACT05', 'arrays', 'error_titles_ARRAY_ACT05', 'script', NULL),
(514, 'error_bodies_ARRAY_ACT05', 'arrays', 'error_bodies_ARRAY_ACT05', 'script', NULL),
(515, 'error_titles_ARRAY_ACT08', 'arrays', 'error_titles_ARRAY_ACT08', 'script', NULL),
(516, 'error_bodies_ARRAY_ACT08', 'arrays', 'error_bodies_ARRAY_ACT08', 'script', NULL),
(517, 'error_titles_ARRAY_ACT09', 'arrays', 'error_titles_ARRAY_ACT09', 'script', NULL),
(518, 'error_bodies_ARRAY_ACT09', 'arrays', 'error_bodies_ARRAY_ACT09', 'script', NULL),
(519, 'error_titles_ARRAY_ACT06', 'arrays', 'error_titles_ARRAY_ACT06', 'script', NULL),
(520, 'error_bodies_ARRAY_ACT06', 'arrays', 'error_bodies_ARRAY_ACT06', 'script', NULL),
(521, 'error_titles_ARRAY_ACT10', 'arrays', 'error_titles_ARRAY_ACT10', 'script', NULL),
(522, 'error_bodies_ARRAY_ACT10', 'arrays', 'error_bodies_ARRAY_ACT10', 'script', NULL),
(523, 'lblDescription', 'backend', 'Label / Description', 'script', NULL),
(524, 'infoUpdateCategoryTitle', 'backend', 'Infobox / Update category', 'script', NULL),
(525, 'infoUpdateCategoryDesc', 'backend', 'Infobox / Update category', 'script', '2015-06-18 11:36:17'),
(526, 'lblDeleteImage', 'backend', 'Label / Delete image', 'script', NULL),
(527, 'lblDeleteImageConfirm', 'backend', 'Label / Delete image', 'script', NULL),
(528, 'buttons_ARRAY_delete', 'arrays', 'buttons_ARRAY_delete', 'script', NULL),
(529, 'buttons_ARRAY_cancel', 'arrays', 'buttons_ARRAY_cancel', 'script', NULL),
(530, 'error_titles_ARRAY_AP01', 'arrays', 'error_titles_ARRAY_AP01', 'script', NULL),
(531, 'error_bodies_ARRAY_AP01', 'arrays', 'error_bodies_ARRAY_AP01', 'script', NULL),
(532, 'error_titles_ARRAY_AP03', 'arrays', 'error_titles_ARRAY_AP03', 'script', NULL),
(533, 'error_bodies_ARRAY_AP03', 'arrays', 'error_bodies_ARRAY_AP03', 'script', '2015-06-18 11:36:38'),
(534, 'error_titles_ARRAY_AP04', 'arrays', 'error_titles_ARRAY_AP04', 'script', NULL),
(535, 'error_bodies_ARRAY_AP04', 'arrays', 'error_bodies_ARRAY_AP04', 'script', NULL),
(536, 'error_titles_ARRAY_AP08', 'arrays', 'error_titles_ARRAY_AP08', 'script', NULL),
(537, 'error_bodies_ARRAY_AP08', 'arrays', 'error_bodies_ARRAY_AP08', 'script', NULL),
(538, 'error_titles_ARRAY_AP05', 'arrays', 'error_titles_ARRAY_AP05', 'script', NULL),
(539, 'error_bodies_ARRAY_AP05', 'arrays', 'error_bodies_ARRAY_AP05', 'script', NULL),
(540, 'error_titles_ARRAY_AP06', 'arrays', 'error_titles_ARRAY_AP06', 'script', NULL),
(541, 'error_bodies_ARRAY_AP06', 'arrays', 'error_bodies_ARRAY_AP06', 'script', NULL),
(542, 'error_titles_ARRAY_AP09', 'arrays', 'error_titles_ARRAY_AP09', 'script', NULL),
(543, 'error_bodies_ARRAY_AP09', 'arrays', 'error_bodies_ARRAY_AP09', 'script', NULL),
(544, 'error_titles_ARRAY_AP10', 'arrays', 'error_titles_ARRAY_AP10', 'script', NULL),
(545, 'error_bodies_ARRAY_AP10', 'arrays', 'error_bodies_ARRAY_AP10', 'script', NULL),
(546, 'infoProductsTitle', 'backend', 'Infobox / List of products', 'script', '2015-06-18 11:28:16'),
(547, 'infoProductsDesc', 'backend', 'Infobox / List of products', 'script', '2015-06-18 11:29:29'),
(548, 'btnPlusAddProduct', 'backend', 'Button / + Add product', 'script', NULL),
(549, 'lblPrice', 'backend', 'Label / Price', 'script', NULL),
(550, 'lblSize', 'backend', 'Label / Size', 'script', NULL),
(551, 'lblCategory', 'backend', 'Label / Category', 'script', NULL),
(552, 'lblNoCategoriesFound', 'backend', 'Label / No categories found', 'script', NULL),
(553, 'lblHere', 'backend', 'Label / here', 'script', NULL),
(554, 'lblSetDifferentSizes', 'backend', 'Label / Set different sizes', 'script', NULL),
(556, 'infoAddProductTitle', 'backend', 'Infobox / Add product', 'script', NULL),
(558, 'infoAddProductDesc', 'backend', 'Infobox / Add product', 'script', '2015-06-18 11:30:24'),
(559, 'btnRemove', 'backend', 'Button / Remove', 'script', NULL),
(562, 'infoUpdateProductTitle', 'backend', 'Infobox / Update product', 'script', NULL),
(563, 'infoUpdateProductDesc', 'backend', 'Infobox / Update product', 'script', '2015-06-18 11:36:52'),
(564, 'infoSpecialOffersTitle', 'backend', 'Infobox / Special offers', 'script', '2015-06-18 11:32:36'),
(565, 'infoSpecialOffersDesc', 'backend', 'Infobox / Special offers', 'script', '2015-06-18 11:33:12'),
(566, 'btnAddSpecialOffer', 'backend', 'Button / + Add special offer', 'script', NULL),
(567, 'lblOfferTitle', 'backend', 'Label / Title', 'script', NULL),
(568, 'error_titles_ARRAY_ASO01', 'arrays', 'error_titles_ARRAY_ASO01', 'script', NULL),
(569, 'error_bodies_ARRAY_ASO01', 'arrays', 'error_bodies_ARRAY_ASO01', 'script', NULL),
(570, 'error_titles_ARRAY_ASO03', 'arrays', 'error_titles_ARRAY_ASO03', 'script', NULL),
(571, 'error_bodies_ARRAY_ASO03', 'arrays', 'error_bodies_ARRAY_ASO03', 'script', '2015-06-18 11:37:18'),
(572, 'error_titles_ARRAY_ASO04', 'arrays', 'error_titles_ARRAY_ASO04', 'script', NULL),
(573, 'error_bodies_ARRAY_ASO04', 'arrays', 'error_bodies_ARRAY_ASO04', 'script', NULL),
(574, 'error_titles_ARRAY_ASO05', 'arrays', 'error_titles_ARRAY_ASO05', 'script', NULL),
(575, 'error_bodies_ARRAY_ASO05', 'arrays', 'error_bodies_ARRAY_ASO05', 'script', NULL),
(576, 'error_titles_ARRAY_ASO08', 'arrays', 'error_titles_ARRAY_ASO08', 'script', NULL),
(577, 'error_bodies_ARRAY_ASO08', 'arrays', 'error_bodies_ARRAY_ASO08', 'script', NULL),
(578, 'error_titles_ARRAY_ASO09', 'arrays', 'error_titles_ARRAY_ASO09', 'script', NULL),
(579, 'error_bodies_ARRAY_ASO09', 'arrays', 'error_bodies_ARRAY_ASO09', 'script', NULL),
(580, 'error_titles_ARRAY_ASO06', 'arrays', 'error_titles_ARRAY_ASO06', 'script', NULL),
(581, 'error_bodies_ARRAY_ASO06', 'arrays', 'error_bodies_ARRAY_ASO06', 'script', NULL),
(582, 'error_titles_ARRAY_ASO10', 'arrays', 'error_titles_ARRAY_ASO10', 'script', NULL),
(583, 'error_bodies_ARRAY_ASO10', 'arrays', 'error_bodies_ARRAY_ASO10', 'script', NULL),
(584, 'lblSameSpecialOffer', 'backend', 'Label / Offer title is already used.', 'script', NULL),
(585, 'infoAddSpecialOfferTitle', 'backend', 'Infobox / Add special offer', 'script', NULL),
(586, 'infoAddSpecialOfferDesc', 'backend', 'Infobox / Add special offer', 'script', '2015-06-18 11:34:51'),
(587, 'lblPeople', 'backend', 'Label / People', 'script', NULL),
(588, 'lblPositiveNumber', 'backend', 'Label / Please enter positive number.', 'script', NULL),
(589, 'infoUpdateSpecialOfferTitle', 'backend', 'Infobox / Update special offer', 'script', NULL),
(590, 'infoUpdateSpecialOfferDesc', 'backend', 'Infobox / Update special offer', 'script', '2015-06-18 11:37:31'),
(591, 'lblProduct', 'backend', 'Label /Product', 'script', NULL),
(592, 'lblInstallJs1_title', 'backend', 'Label / Install title', 'script', NULL),
(593, 'lblInstallJs1_body', 'backend', 'Label / Install body', 'script', NULL),
(594, 'lblInstallConfig', 'backend', 'Label / Language', 'script', NULL),
(595, 'lblInstallConfigLocale', 'backend', 'Label / Language', 'script', NULL),
(596, 'lblInstallConfigHide', 'backend', 'Label / Hide language selector', 'script', NULL),
(597, 'front_menu', 'frontend', 'Label / Menu', 'script', NULL),
(598, 'front_special_offers', 'frontend', 'Label / Special offers', 'script', NULL),
(599, 'front_category', 'frontend', 'Label / Category', 'script', NULL),
(600, 'front_all_categories', 'frontend', 'Label / All categories', 'script', NULL),
(601, 'front_language', 'frontend', 'Label / Language', 'script', NULL),
(602, 'front_menu_title', 'frontend', 'Label / Menu Title Here', 'script', NULL),
(603, 'front_menu_desc', 'frontend', 'Label / Menu description', 'script', NULL),
(604, 'front_no_menus_available', 'frontend', 'Label / Menu is not available.', 'script', NULL),
(605, 'front_offer_title', 'frontend', 'Label / Special offers', 'script', NULL),
(606, 'front_offer_desc', 'frontend', 'Label / Offer description', 'script', NULL),
(607, 'front_people', 'frontend', 'Label / people', 'script', NULL),
(608, 'front_person', 'frontend', 'Label / person', 'script', NULL),
(609, 'front_product_not_found', 'frontend', 'Label / Product not found', 'script', NULL),
(610, 'front_offer_not_found', 'frontend', 'Label / Special offer not found!', 'script', NULL),
(611, 'lblNoProductsMessage', 'backend', 'Label / No product message', 'script', NULL),
(612, 'lblAddAsMainCategory', 'backend', 'Label / Add as main category', 'script', NULL),
(613, 'lblSelectProduct', 'backend', 'Label / Select product', 'script', NULL),
(614, 'lblSelectSize', 'backend', 'Label / Select size', 'script', NULL);

INSERT INTO `menu_builder_multi_lang` (`id`, `foreign_id`, `model`, `locale`, `field`, `content`, `source`) VALUES
(1, 1, 'pjField', 1, 'title', 'Add language', 'script'),
(4, 2, 'pjField', 1, 'title', 'Password reminder', 'script'),
(7, 3, 'pjField', 1, 'title', 'Admin Login', 'script'),
(10, 4, 'pjField', 1, 'title', 'Back-end titles', 'script'),
(13, 5, 'pjField', 1, 'title', 'Add +', 'script'),
(16, 6, 'pjField', 1, 'title', '« Back', 'script'),
(19, 7, 'pjField', 1, 'title', 'Backup', 'script'),
(22, 8, 'pjField', 1, 'title', 'Cancel', 'script'),
(25, 9, 'pjField', 1, 'title', 'Continue', 'script'),
(28, 10, 'pjField', 1, 'title', 'Delete', 'script'),
(31, 11, 'pjField', 1, 'title', 'Login', 'script'),
(34, 12, 'pjField', 1, 'title', 'Reset', 'script'),
(37, 13, 'pjField', 1, 'title', 'Save', 'script'),
(40, 14, 'pjField', 1, 'title', 'Search', 'script'),
(43, 15, 'pjField', 1, 'title', 'Send', 'script'),
(46, 16, 'pjField', 1, 'title', 'Update', 'script'),
(49, 17, 'pjField', 1, 'title', 'DateTime', 'script'),
(52, 18, 'pjField', 1, 'title', 'Email', 'script'),
(55, 19, 'pjField', 1, 'title', 'Dear {Name},Your password: {Password}', 'script'),
(58, 20, 'pjField', 1, 'title', 'Password reminder', 'script'),
(61, 21, 'pjField', 1, 'title', 'Front-end titles', 'script'),
(64, 22, 'pjField', 1, 'title', 'Action confirmation', 'script'),
(67, 23, 'pjField', 1, 'title', 'Cancel', 'script'),
(70, 24, 'pjField', 1, 'title', 'Delete', 'script'),
(73, 25, 'pjField', 1, 'title', 'OK', 'script'),
(76, 26, 'pjField', 1, 'title', 'Choose Action', 'script'),
(79, 27, 'pjField', 1, 'title', 'Are you sure you want to delete selected record?', 'script'),
(82, 28, 'pjField', 1, 'title', 'Delete confirmation', 'script'),
(85, 29, 'pjField', 1, 'title', 'No records found', 'script'),
(88, 30, 'pjField', 1, 'title', 'Go to page:', 'script'),
(91, 31, 'pjField', 1, 'title', 'Items per page', 'script'),
(94, 32, 'pjField', 1, 'title', 'Next »', 'script'),
(97, 33, 'pjField', 1, 'title', 'Next page', 'script'),
(100, 34, 'pjField', 1, 'title', '« Prev', 'script'),
(103, 35, 'pjField', 1, 'title', 'Prev page', 'script'),
(106, 36, 'pjField', 1, 'title', 'Total items:', 'script'),
(109, 37, 'pjField', 1, 'title', 'You can show a map with the location of the listing accommodation on the listing details page. Submit the full address first and then click on ''Get coordinates from Google Maps API'' button. Save your data.', 'script'),
(112, 38, 'pjField', 1, 'title', 'Location and address', 'script'),
(115, 39, 'pjField', 1, 'title', 'Listing Bookings Body', 'script'),
(118, 40, 'pjField', 1, 'title', 'Listing Bookings Title', 'script'),
(121, 41, 'pjField', 1, 'title', 'Listing Contact Body', 'script'),
(124, 42, 'pjField', 1, 'title', 'Listing Contact Title', 'script'),
(127, 43, 'pjField', 1, 'title', 'Extend exp.date Body', 'script'),
(130, 44, 'pjField', 1, 'title', 'Extend exp.date Title', 'script'),
(133, 45, 'pjField', 1, 'title', 'Listing Prices Body', 'script'),
(136, 46, 'pjField', 1, 'title', 'Listing Prices Title', 'script'),
(139, 47, 'pjField', 1, 'title', 'Languages Array Body', 'script'),
(142, 48, 'pjField', 1, 'title', 'Languages Arrays Title', 'script'),
(145, 49, 'pjField', 1, 'title', 'Languages Backend Body', 'script'),
(148, 50, 'pjField', 1, 'title', 'Languages Backend Title', 'script'),
(151, 51, 'pjField', 1, 'title', 'Languages Body', 'script'),
(154, 52, 'pjField', 1, 'title', 'Languages Frontend Body', 'script'),
(157, 53, 'pjField', 1, 'title', 'Languages Frontend Title', 'script'),
(160, 54, 'pjField', 1, 'title', 'Languages Title', 'script'),
(163, 55, 'pjField', 1, 'title', 'Add user', 'script'),
(166, 56, 'pjField', 1, 'title', 'Backup database', 'script'),
(169, 57, 'pjField', 1, 'title', 'Backup files', 'script'),
(172, 58, 'pjField', 1, 'title', 'Choose', 'script'),
(175, 59, 'pjField', 1, 'title', 'days', 'script'),
(178, 60, 'pjField', 1, 'title', 'Delete', 'script'),
(181, 61, 'pjField', 1, 'title', 'Error', 'script'),
(184, 62, 'pjField', 1, 'title', 'Export', 'script'),
(187, 63, 'pjField', 1, 'title', 'Forgot password', 'script'),
(190, 64, 'pjField', 1, 'title', 'IP address', 'script'),
(193, 65, 'pjField', 1, 'title', 'Is confirmed', 'script'),
(196, 66, 'pjField', 1, 'title', 'Name', 'script'),
(199, 67, 'pjField', 1, 'title', 'No', 'script'),
(202, 68, 'pjField', 1, 'title', 'Option', 'script'),
(205, 69, 'pjField', 1, 'title', 'Option list', 'script'),
(208, 70, 'pjField', 1, 'title', 'Role', 'script'),
(211, 71, 'pjField', 1, 'title', 'Status', 'script'),
(214, 72, 'pjField', 1, 'title', 'Type', 'script'),
(217, 73, 'pjField', 1, 'title', 'Update user', 'script'),
(220, 74, 'pjField', 1, 'title', 'Registration date/time', 'script'),
(223, 75, 'pjField', 1, 'title', 'Value', 'script'),
(226, 76, 'pjField', 1, 'title', 'Yes', 'script'),
(229, 77, 'pjField', 1, 'title', 'Back', 'script'),
(232, 78, 'pjField', 1, 'title', 'Arrays titles', 'script'),
(235, 79, 'pjField', 1, 'title', 'Languages', 'script'),
(238, 80, 'pjField', 1, 'title', 'Flag', 'script'),
(241, 81, 'pjField', 1, 'title', 'Is default', 'script'),
(244, 82, 'pjField', 1, 'title', 'Order', 'script'),
(247, 83, 'pjField', 1, 'title', 'Title', 'script'),
(250, 84, 'pjField', 1, 'title', 'Backup', 'script'),
(253, 85, 'pjField', 1, 'title', 'Dashboard', 'script'),
(256, 86, 'pjField', 1, 'title', 'Multi Lang', 'script'),
(259, 87, 'pjField', 1, 'title', 'Languages', 'script'),
(262, 88, 'pjField', 1, 'title', 'Logout', 'script'),
(265, 89, 'pjField', 1, 'title', 'Options', 'script'),
(268, 90, 'pjField', 1, 'title', 'Plugins', 'script'),
(271, 91, 'pjField', 1, 'title', 'Profile', 'script'),
(274, 92, 'pjField', 1, 'title', 'Users', 'script'),
(277, 93, 'pjField', 1, 'title', 'Click on the flag icon to choose which language version of the content you wish to edit.', 'script'),
(280, 94, 'pjField', 1, 'title', 'Currency', 'script'),
(283, 95, 'pjField', 1, 'title', 'Date format', 'script'),
(286, 96, 'pjField', 1, 'title', 'Send email', 'script'),
(289, 97, 'pjField', 1, 'title', 'SMTP Host', 'script'),
(292, 98, 'pjField', 1, 'title', 'SMTP Password', 'script'),
(295, 99, 'pjField', 1, 'title', 'SMTP Port', 'script'),
(298, 100, 'pjField', 1, 'title', 'SMTP Username', 'script'),
(301, 101, 'pjField', 1, 'title', 'Timezone', 'script'),
(304, 102, 'pjField', 1, 'title', 'First day of the week', 'script'),
(307, 103, 'pjField', 1, 'title', 'Password', 'script'),
(310, 125, 'pjField', 1, 'title', 'Revert status', 'script'),
(313, 126, 'pjField', 1, 'title', 'URL', 'script'),
(316, 127, 'pjField', 1, 'title', 'Username', 'script'),
(319, 128, 'pjField', 1, 'title', 'User with such email address exists.', 'script'),
(322, 129, 'pjField', 1, 'title', 'Sunday', 'script'),
(325, 130, 'pjField', 1, 'title', 'Monday', 'script'),
(328, 131, 'pjField', 1, 'title', 'Tuesday', 'script'),
(331, 132, 'pjField', 1, 'title', 'Wednesday', 'script'),
(334, 133, 'pjField', 1, 'title', 'Thursday', 'script'),
(337, 134, 'pjField', 1, 'title', 'Friday', 'script'),
(340, 135, 'pjField', 1, 'title', 'Saturday', 'script'),
(343, 136, 'pjField', 1, 'title', 'S', 'script'),
(346, 137, 'pjField', 1, 'title', 'M', 'script'),
(349, 138, 'pjField', 1, 'title', 'T', 'script'),
(352, 139, 'pjField', 1, 'title', 'W', 'script'),
(355, 140, 'pjField', 1, 'title', 'T', 'script'),
(358, 141, 'pjField', 1, 'title', 'F', 'script'),
(361, 142, 'pjField', 1, 'title', 'S', 'script'),
(364, 143, 'pjField', 1, 'title', 'Given email address is not associated with any account.', 'script'),
(367, 144, 'pjField', 1, 'title', 'For further instructions please check your mailbox.', 'script'),
(370, 145, 'pjField', 1, 'title', 'We are sorry, please try again later.', 'script'),
(373, 146, 'pjField', 1, 'title', 'All the changes made to your profile have been saved.', 'script'),
(376, 147, 'pjField', 1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at ligula non arcu dignissim pretium. Praesent in magna nulla, in porta leo.', 'script'),
(379, 148, 'pjField', 1, 'title', 'All backup files have been saved.', 'script'),
(382, 149, 'pjField', 1, 'title', 'No option was selected.', 'script'),
(385, 150, 'pjField', 1, 'title', 'Backup not performed.', 'script'),
(388, 151, 'pjField', 1, 'title', 'All the changes made to titles have been saved.', 'script'),
(391, 152, 'pjField', 1, 'title', 'All the changes made to options have been saved.', 'script'),
(394, 153, 'pjField', 1, 'title', 'All the changes made to this user have been saved.', 'script'),
(397, 154, 'pjField', 1, 'title', 'All the changes made to this user have been saved.', 'script'),
(400, 155, 'pjField', 1, 'title', 'We are sorry, but the user has not been added.', 'script'),
(403, 156, 'pjField', 1, 'title', 'User your looking for is missing.', 'script'),
(406, 159, 'pjField', 1, 'title', 'Account not found!', 'script'),
(409, 160, 'pjField', 1, 'title', 'Password send!', 'script'),
(412, 161, 'pjField', 1, 'title', 'Password not send!', 'script'),
(415, 162, 'pjField', 1, 'title', 'Profile updated!', 'script'),
(418, 163, 'pjField', 1, 'title', 'Backup', 'script'),
(421, 164, 'pjField', 1, 'title', 'Backup complete!', 'script'),
(424, 165, 'pjField', 1, 'title', 'Backup failed!', 'script'),
(427, 166, 'pjField', 1, 'title', 'Backup failed!', 'script'),
(430, 167, 'pjField', 1, 'title', 'Options updated!', 'script'),
(433, 168, 'pjField', 1, 'title', 'User updated!', 'script'),
(436, 169, 'pjField', 1, 'title', 'User added!', 'script'),
(439, 170, 'pjField', 1, 'title', 'User failed to add.', 'script'),
(442, 171, 'pjField', 1, 'title', 'User not found.', 'script'),
(445, 174, 'pjField', 1, 'title', 'Active', 'script'),
(448, 175, 'pjField', 1, 'title', 'Inactive', 'script'),
(451, 176, 'pjField', 1, 'title', 'Wrong username or password', 'script'),
(454, 177, 'pjField', 1, 'title', 'Access denied', 'script'),
(457, 178, 'pjField', 1, 'title', 'Account is disabled', 'script'),
(460, 179, 'pjField', 1, 'title', 'January', 'script'),
(463, 180, 'pjField', 1, 'title', 'October', 'script'),
(466, 181, 'pjField', 1, 'title', 'November', 'script'),
(469, 182, 'pjField', 1, 'title', 'December', 'script'),
(472, 183, 'pjField', 1, 'title', 'February', 'script'),
(475, 184, 'pjField', 1, 'title', 'March', 'script'),
(478, 185, 'pjField', 1, 'title', 'April', 'script'),
(481, 186, 'pjField', 1, 'title', 'May', 'script'),
(484, 187, 'pjField', 1, 'title', 'June', 'script'),
(487, 188, 'pjField', 1, 'title', 'July', 'script'),
(490, 189, 'pjField', 1, 'title', 'August', 'script'),
(493, 190, 'pjField', 1, 'title', 'September', 'script'),
(496, 191, 'pjField', 1, 'title', 'Dr.', 'script'),
(499, 192, 'pjField', 1, 'title', 'Miss', 'script'),
(502, 193, 'pjField', 1, 'title', 'Mr.', 'script'),
(505, 194, 'pjField', 1, 'title', 'Mrs.', 'script'),
(508, 195, 'pjField', 1, 'title', 'Ms.', 'script'),
(511, 196, 'pjField', 1, 'title', 'Other', 'script'),
(514, 197, 'pjField', 1, 'title', 'Prof.', 'script'),
(517, 198, 'pjField', 1, 'title', 'Rev.', 'script'),
(520, 199, 'pjField', 1, 'title', 'Jan', 'script'),
(523, 200, 'pjField', 1, 'title', 'Oct', 'script'),
(526, 201, 'pjField', 1, 'title', 'Nov', 'script'),
(529, 202, 'pjField', 1, 'title', 'Dec', 'script'),
(532, 203, 'pjField', 1, 'title', 'Feb', 'script'),
(535, 204, 'pjField', 1, 'title', 'Mar', 'script'),
(538, 205, 'pjField', 1, 'title', 'Apr', 'script'),
(541, 206, 'pjField', 1, 'title', 'May', 'script'),
(544, 207, 'pjField', 1, 'title', 'Jun', 'script'),
(547, 208, 'pjField', 1, 'title', 'Jul', 'script'),
(550, 209, 'pjField', 1, 'title', 'Aug', 'script'),
(553, 210, 'pjField', 1, 'title', 'Sep', 'script'),
(556, 211, 'pjField', 1, 'title', 'You are not loged in.', 'script'),
(559, 212, 'pjField', 1, 'title', 'Your hosting account does not allow uploading such a large image.', 'script'),
(562, 213, 'pjField', 1, 'title', 'Access denied. You have not requisite rights to.', 'script'),
(565, 214, 'pjField', 1, 'title', 'Empty resultset.', 'script'),
(568, 215, 'pjField', 1, 'title', 'The operation is not allowed in demo mode.', 'script'),
(571, 216, 'pjField', 1, 'title', 'No property for the reservation found', 'script'),
(574, 217, 'pjField', 1, 'title', 'No reservation found', 'script'),
(577, 218, 'pjField', 1, 'title', 'No permisions to edit the reservation', 'script'),
(580, 219, 'pjField', 1, 'title', 'No permisions to edit the property', 'script'),
(583, 220, 'pjField', 1, 'title', 'E-Mail address already exist', 'script'),
(586, 221, 'pjField', 1, 'title', 'Your registration was successfull. Your account needs to be approved.', 'script'),
(589, 222, 'pjField', 1, 'title', 'Your registration was successfull.', 'script'),
(592, 223, 'pjField', 1, 'title', 'GMT-03:00', 'script'),
(595, 224, 'pjField', 1, 'title', 'GMT-04:00', 'script'),
(598, 225, 'pjField', 1, 'title', 'GMT-05:00', 'script'),
(601, 226, 'pjField', 1, 'title', 'GMT-06:00', 'script'),
(604, 227, 'pjField', 1, 'title', 'GMT-07:00', 'script'),
(607, 228, 'pjField', 1, 'title', 'GMT-08:00', 'script'),
(610, 229, 'pjField', 1, 'title', 'GMT-09:00', 'script'),
(613, 230, 'pjField', 1, 'title', 'GMT-01:00', 'script'),
(616, 231, 'pjField', 1, 'title', 'GMT-10:00', 'script'),
(619, 232, 'pjField', 1, 'title', 'GMT-11:00', 'script'),
(622, 233, 'pjField', 1, 'title', 'GMT-12:00', 'script'),
(625, 234, 'pjField', 1, 'title', 'GMT-02:00', 'script'),
(628, 235, 'pjField', 1, 'title', 'GMT', 'script'),
(631, 236, 'pjField', 1, 'title', 'GMT+03:00', 'script'),
(634, 237, 'pjField', 1, 'title', 'GMT+04:00', 'script'),
(637, 238, 'pjField', 1, 'title', 'GMT+05:00', 'script'),
(640, 239, 'pjField', 1, 'title', 'GMT+06:00', 'script'),
(643, 240, 'pjField', 1, 'title', 'GMT+07:00', 'script'),
(646, 241, 'pjField', 1, 'title', 'GMT+08:00', 'script'),
(649, 242, 'pjField', 1, 'title', 'GMT+09:00', 'script'),
(652, 243, 'pjField', 1, 'title', 'GMT+01:00', 'script'),
(655, 244, 'pjField', 1, 'title', 'GMT+10:00', 'script'),
(658, 245, 'pjField', 1, 'title', 'GMT+11:00', 'script'),
(661, 246, 'pjField', 1, 'title', 'GMT+12:00', 'script'),
(664, 247, 'pjField', 1, 'title', 'GMT+13:00', 'script'),
(667, 248, 'pjField', 1, 'title', 'GMT+02:00', 'script'),
(670, 249, 'pjField', 1, 'title', 'Inactive', 'script'),
(673, 250, 'pjField', 1, 'title', 'Active', 'script'),
(676, 251, 'pjField', 1, 'title', 'No', 'script'),
(679, 252, 'pjField', 1, 'title', 'Yes', 'script'),
(682, 253, 'pjField', 1, 'title', 'Delete selected', 'script'),
(685, 254, 'pjField', 1, 'title', 'Are you sure that you want to delete selected record(s)?', 'script'),
(688, 255, 'pjField', 1, 'title', 'All', 'script'),
(691, 256, 'pjField', 1, 'title', 'Client with such email address exists.', 'script'),
(694, 308, 'pjField', 1, 'title', 'Last login', 'script'),
(697, 360, 'pjField', 1, 'title', 'Install', 'script'),
(700, 361, 'pjField', 1, 'title', 'Preview', 'script'),
(703, 480, 'pjField', 1, 'title', 'List of users', 'script'),
(706, 481, 'pjField', 1, 'title', 'Below you can see users who have access to the Menu Builder administration pages. Click on "+ Add user" button to add a new user.', 'script'),
(709, 482, 'pjField', 1, 'title', '+ Add user', 'script'),
(712, 483, 'pjField', 1, 'title', 'No records selected', 'script'),
(715, 484, 'pjField', 1, 'title', 'You need to select at least a single record.', 'script'),
(718, 485, 'pjField', 1, 'title', 'Add user', 'script'),
(721, 486, 'pjField', 1, 'title', 'Fill in the form to add a new user.', 'script'),
(724, 487, 'pjField', 1, 'title', 'Phone', 'script'),
(727, 488, 'pjField', 1, 'title', 'Update user', 'script'),
(730, 489, 'pjField', 1, 'title', 'You can make any change on the form below and click "Save" button to update user information.', 'script'),
(733, 490, 'pjField', 1, 'title', 'General', 'script'),
(736, 491, 'pjField', 1, 'title', 'General options', 'script'),
(739, 492, 'pjField', 1, 'title', 'Here you can set the General options for the Menu Builder.', 'script'),
(742, 493, 'pjField', 1, 'title', 'Time format', 'script'),
(745, 494, 'pjField', 1, 'title', 'Products', 'script'),
(748, 495, 'pjField', 1, 'title', 'Categories', 'script'),
(751, 496, 'pjField', 1, 'title', 'Special offers', 'script'),
(754, 497, 'pjField', 1, 'title', '+ Add category', 'script'),
(757, 498, 'pjField', 1, 'title', 'Categories', 'script'),
(760, 499, 'pjField', 1, 'title', 'You can create different categories to organize the products in your menu.', 'script'),
(763, 500, 'pjField', 1, 'title', 'Category title', 'script'),
(766, 501, 'pjField', 1, 'title', 'This field is required.', 'script'),
(769, 502, 'pjField', 1, 'title', 'Category title is already used.', 'script'),
(772, 503, 'pjField', 1, 'title', 'Add category', 'script'),
(775, 504, 'pjField', 1, 'title', 'Create a new category by adding its name, description and image. You can create a main category or a sub-category. One level sub-categories are supported.', 'script'),
(778, 505, 'pjField', 1, 'title', 'Parent category', 'script'),
(781, 506, 'pjField', 1, 'title', 'Image', 'script'),
(784, 507, 'pjField', 1, 'title', 'Category updated', 'script'),
(787, 508, 'pjField', 1, 'title', 'All changes made to category have been saved.', 'script'),
(790, 509, 'pjField', 1, 'title', 'Category added', 'script'),
(793, 510, 'pjField', 1, 'title', 'Category has been added successfully.', 'script'),
(796, 511, 'pjField', 1, 'title', 'Category failed to added', 'script'),
(799, 512, 'pjField', 1, 'title', 'Category could not be added. Please try again.', 'script'),
(802, 513, 'pjField', 1, 'title', 'Image size too big', 'script'),
(805, 514, 'pjField', 1, 'title', 'New category could not be added because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(808, 515, 'pjField', 1, 'title', 'Category not found', 'script'),
(811, 516, 'pjField', 1, 'title', 'We are sorry that category you are looking for is missing.', 'script'),
(814, 517, 'pjField', 1, 'title', 'Upload error', 'script'),
(817, 518, 'pjField', 1, 'title', 'New category has been added, but image could not be uploaded successfully.', 'script'),
(820, 519, 'pjField', 1, 'title', 'Image size too big', 'script'),
(823, 520, 'pjField', 1, 'title', 'The category could not be updated successfully because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(826, 521, 'pjField', 1, 'title', 'Upload error', 'script'),
(829, 522, 'pjField', 1, 'title', 'The category has been updated, but image could not be uploaded successfully.', 'script'),
(832, 523, 'pjField', 1, 'title', 'Description', 'script'),
(835, 524, 'pjField', 1, 'title', 'Update category', 'script'),
(838, 525, 'pjField', 1, 'title', 'Use the form below to change category details.', 'script'),
(841, 526, 'pjField', 1, 'title', 'Delete image', 'script'),
(844, 527, 'pjField', 1, 'title', 'Are you sure that you want to delete this image?', 'script'),
(847, 528, 'pjField', 1, 'title', 'Delete', 'script'),
(850, 529, 'pjField', 1, 'title', 'Cancel', 'script'),
(853, 530, 'pjField', 1, 'title', 'Product updated', 'script'),
(856, 531, 'pjField', 1, 'title', 'All changes to the product have been saved.', 'script'),
(859, 532, 'pjField', 1, 'title', 'Product added', 'script'),
(862, 533, 'pjField', 1, 'title', 'Product has been added successfully.', 'script'),
(865, 534, 'pjField', 1, 'title', 'Product failed to add', 'script'),
(868, 535, 'pjField', 1, 'title', 'We are sorry that new product could not be added successfully.', 'script'),
(871, 536, 'pjField', 1, 'title', 'Product not found', 'script'),
(874, 537, 'pjField', 1, 'title', 'We are sorry that product you are looking for is missing.', 'script'),
(877, 538, 'pjField', 1, 'title', 'Image size too large', 'script'),
(880, 539, 'pjField', 1, 'title', 'New product could not be added because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(883, 540, 'pjField', 1, 'title', 'Image size too large', 'script'),
(886, 541, 'pjField', 1, 'title', 'The product could not be updated successfully because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(889, 542, 'pjField', 1, 'title', 'Upload error', 'script'),
(892, 543, 'pjField', 1, 'title', 'New product has been added, but image could not be uploaded successfully.', 'script'),
(895, 544, 'pjField', 1, 'title', 'Upload error', 'script'),
(898, 545, 'pjField', 1, 'title', 'The product has been updated, but image could not be uploaded successfully.', 'script'),
(901, 546, 'pjField', 1, 'title', 'Products', 'script'),
(904, 547, 'pjField', 1, 'title', 'Below you can find a list with all products in the menu. You can add as many items as you wish, delete or edit existing products.', 'script'),
(907, 548, 'pjField', 1, 'title', '+ Add product', 'script'),
(910, 549, 'pjField', 1, 'title', 'Price', 'script'),
(913, 550, 'pjField', 1, 'title', 'Size', 'script'),
(916, 551, 'pjField', 1, 'title', 'Category', 'script'),
(919, 552, 'pjField', 1, 'title', 'No categories found. Add a category', 'script'),
(922, 553, 'pjField', 1, 'title', 'here', 'script'),
(925, 554, 'pjField', 1, 'title', 'Set different sizes', 'script'),
(928, 556, 'pjField', 1, 'title', 'Add product', 'script'),
(931, 558, 'pjField', 1, 'title', 'Use the form below to add new product. You can add product name, description, upload an image, and price based on meal size.', 'script'),
(934, 559, 'pjField', 1, 'title', 'Remove', 'script'),
(937, 562, 'pjField', 1, 'title', 'Update product', 'script'),
(940, 563, 'pjField', 1, 'title', 'Use the form below to update product details.', 'script'),
(943, 564, 'pjField', 1, 'title', 'Special Offers', 'script'),
(946, 565, 'pjField', 1, 'title', 'Below you can see all available special offers. You can create unlimited number of special offers.', 'script'),
(949, 566, 'pjField', 1, 'title', '+ Add special offer', 'script'),
(952, 567, 'pjField', 1, 'title', 'Title', 'script'),
(955, 568, 'pjField', 1, 'title', 'Special offer updated', 'script'),
(958, 569, 'pjField', 1, 'title', 'All changes made to special offer have been saved.', 'script'),
(961, 570, 'pjField', 1, 'title', 'Special offer added', 'script'),
(964, 571, 'pjField', 1, 'title', 'Special offer has been added successfully.', 'script'),
(967, 572, 'pjField', 1, 'title', 'Special offer failed to added', 'script'),
(970, 573, 'pjField', 1, 'title', 'Special offer could not be added. Please try again.', 'script'),
(973, 574, 'pjField', 1, 'title', 'Image size too big', 'script'),
(976, 575, 'pjField', 1, 'title', 'New special offer could not be added because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(979, 576, 'pjField', 1, 'title', 'Special offer not found', 'script'),
(982, 577, 'pjField', 1, 'title', 'We are sorry that special offer you are looking for is missing.', 'script'),
(985, 578, 'pjField', 1, 'title', 'Upload error', 'script'),
(988, 579, 'pjField', 1, 'title', 'New special offer has been added, but image could not be uploaded successfully.', 'script'),
(991, 580, 'pjField', 1, 'title', 'Image size too big', 'script'),
(994, 581, 'pjField', 1, 'title', 'The special offer could not be updated successfully because image size is too large and your server cannot upload it. Maximum allowed size is {SIZE}. Please, upload smaller image.', 'script'),
(997, 582, 'pjField', 1, 'title', 'Upload error', 'script'),
(1000, 583, 'pjField', 1, 'title', 'The special offer has been updated, but image could not be uploaded successfully.', 'script'),
(1003, 584, 'pjField', 1, 'title', 'Offer title is already used.', 'script'),
(1006, 585, 'pjField', 1, 'title', 'Add special offer', 'script'),
(1009, 586, 'pjField', 1, 'title', 'For each special offer you can add title, description, number of people offer is valid for, price, image and products it includes.', 'script'),
(1012, 587, 'pjField', 1, 'title', 'People', 'script'),
(1015, 588, 'pjField', 1, 'title', 'Please enter positive number.', 'script'),
(1018, 589, 'pjField', 1, 'title', 'Update special offer', 'script'),
(1021, 590, 'pjField', 1, 'title', 'Use the form below to edit special offer details.', 'script'),
(1024, 591, 'pjField', 1, 'title', 'Product', 'script'),
(1027, 592, 'pjField', 1, 'title', 'Install instructions', 'script'),
(1030, 593, 'pjField', 1, 'title', 'Copy the code below and put it on the web page where you want the menu to appear. If you have a multi language menu script you can select the default language and to hide the language selector.', 'script'),
(1033, 594, 'pjField', 1, 'title', 'Language', 'script'),
(1036, 595, 'pjField', 1, 'title', 'Language', 'script'),
(1039, 596, 'pjField', 1, 'title', 'Hide language selector', 'script'),
(1042, 597, 'pjField', 1, 'title', 'Menu', 'script'),
(1045, 598, 'pjField', 1, 'title', 'Special offers', 'script'),
(1048, 599, 'pjField', 1, 'title', 'Category', 'script'),
(1051, 600, 'pjField', 1, 'title', 'All categories', 'script'),
(1054, 601, 'pjField', 1, 'title', 'Language', 'script'),
(1057, 602, 'pjField', 1, 'title', 'Menu Title Here', 'script'),
(1060, 603, 'pjField', 1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea ', 'script'),
(1063, 604, 'pjField', 1, 'title', 'Menu is not available.', 'script'),
(1066, 605, 'pjField', 1, 'title', 'Special offers', 'script'),
(1069, 606, 'pjField', 1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea ', 'script'),
(1072, 607, 'pjField', 1, 'title', 'people', 'script'),
(1075, 608, 'pjField', 1, 'title', 'person', 'script'),
(1078, 609, 'pjField', 1, 'title', 'No products found', 'script'),
(1081, 610, 'pjField', 1, 'title', 'Special offer not found!', 'script'),
(1084, 611, 'pjField', 1, 'title', 'No products available. To add one click {STAG}here{ETAG}', 'script'),
(1087, 612, 'pjField', 1, 'title', 'Add as main category', 'script'),
(1090, 613, 'pjField', 1, 'title', 'Select product', 'script'),
(1093, 614, 'pjField', 1, 'title', 'Select size', 'script');

INSERT INTO `menu_builder_options` (`foreign_id`, `key`, `tab_id`, `value`, `label`, `type`, `order`, `is_visible`, `style`) VALUES
(1, 'o_currency', 2, 'AED|AFN|ALL|AMD|ANG|AOA|ARS|AUD|AWG|AZN|BAM|BBD|BDT|BGN|BHD|BIF|BMD|BND|BOB|BOV|BRL|BSD|BTN|BWP|BYR|BZD|CAD|CDF|CHE|CHF|CHW|CLF|CLP|CNY|COP|COU|CRC|CUC|CUP|CVE|CZK|DJF|DKK|DOP|DZD|EEK|EGP|ERN|ETB|EUR|FJD|FKP|GBP|GEL|GHS|GIP|GMD|GNF|GTQ|GYD|HKD|HNL|HRK|HTG|HUF|IDR|ILS|INR|IQD|IRR|ISK|JMD|JOD|JPY|KES|KGS|KHR|KMF|KPW|KRW|KWD|KYD|KZT|LAK|LBP|LKR|LRD|LSL|LTL|LVL|LYD|MAD|MDL|MGA|MKD|MMK|MNT|MOP|MRO|MUR|MVR|MWK|MXN|MXV|MYR|MZN|NAD|NGN|NIO|NOK|NPR|NZD|OMR|PAB|PEN|PGK|PHP|PKR|PLN|PYG|QAR|RON|RSD|RUB|RWF|SAR|SBD|SCR|SDG|SEK|SGD|SHP|SLL|SOS|SRD|STD|SYP|SZL|THB|TJS|TMT|TND|TOP|TRY|TTD|TWD|TZS|UAH|UGX|USD|USN|USS|UYU|UZS|VEF|VND|VUV|WST|XAF|XAG|XAU|XBA|XBB|XBC|XBD|XCD|XDR|XFU|XOF|XPD|XPF|XPT|XTS|XXX|YER|ZAR|ZMK|ZWL::EUR', NULL, 'enum', 1, 1, NULL),
(1, 'o_date_format', 1, 'd.m.Y|m.d.Y|Y.m.d|j.n.Y|n.j.Y|Y.n.j|d/m/Y|m/d/Y|Y/m/d|j/n/Y|n/j/Y|Y/n/j|d-m-Y|m-d-Y|Y-m-d|j-n-Y|n-j-Y|Y-n-j::d-m-Y', 'd.m.Y (25.09.2012)|m.d.Y (09.25.2012)|Y.m.d (2012.09.25)|j.n.Y (25.9.2012)|n.j.Y (9.25.2012)|Y.n.j (2012.9.25)|d/m/Y (25/09/2012)|m/d/Y (09/25/2012)|Y/m/d (2012/09/25)|j/n/Y (25/9/2012)|n/j/Y (9/25/2012)|Y/n/j (2012/9/25)|d-m-Y (25-09-2012)|m-d-Y (09-25-2012)|Y-m-d (2012-09-25)|j-n-Y (25-9-2012)|n-j-Y (9-25-2012)|Y-n-j (2012-9-25)', 'enum', 2, 1, NULL),
(1, 'o_time_format', 1, 'H:i|G:i|h:i|h:i a|h:i A|g:i|g:i a|g:i A::H:i', 'H:i (09:45)|G:i (9:45)|h:i (09:45)|h:i a (09:45 am)|h:i A (09:45 AM)|g:i (9:45)|g:i a (9:45 am)|g:i A (9:45 AM)', 'enum', 3, 1, NULL),
(1, 'o_timezone', 1, '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', 4, 1, NULL),
(1, 'o_week_start', 1, '0|1|2|3|4|5|6::1', 'Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday', 'enum', 5, 1, NULL),
(1, 'o_theme', 1, 'theme1|theme2|theme3|theme4|theme5|theme6|theme7|theme8|theme9|theme10|theme11::theme1', 'Theme 1|Theme 2|Theme 3|Theme 4|Theme 5|Theme 6|Theme 7|Theme 8|Theme 9|Theme 10|Theme 11', 'enum', 6, 0, NULL),
(1, 'o_send_email', 1, 'mail|smtp::mail', 'PHP mail()|SMTP', 'enum', 7, 1, NULL),
(1, 'o_smtp_host', 1, NULL, NULL, 'string', 8, 1, NULL),
(1, 'o_smtp_pass', 1, NULL, NULL, 'string', 9, 1, NULL),
(1, 'o_smtp_port', 1, '25', NULL, 'int', 10, 1, NULL),
(1, 'o_smtp_user', 1, NULL, NULL, 'string', 11, 1, NULL),

(1, 'o_multi_lang', 99, '1|0::1', NULL, 'enum', NULL, 1, NULL),
(1, 'o_fields_index', 99, 'd874fcc5fe73b90d770a544664a3775d', NULL, 'string', NULL, 0, NULL);

INSERT INTO `menu_builder_roles` (`id`, `role`, `status`) VALUES
(1, 'admin', 'T'),
(2, 'editor', 'T');